name: Auto-Update Vector Database Weekly & Deploy to Hugging Face

on:
  schedule:
    - cron: "0 0 * * 1"  # Runs every Monday at midnight UTC
  workflow_dispatch:  # Allows manual trigger from GitHub Actions

jobs:
  update-database:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Install Dependencies
      run: pip install -r requirements.txt

    - name: Fetch Trending Movies
      env:
        TMDB_API_KEY: ${{ secrets.TMDB_API_KEY }}
      run: python fetch_movies.py

    - name: Generate Movie Embeddings
      env:
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      run: python generate_embeddings.py

    - name: Store Embeddings in ChromaDB
      env:
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      run: python store_in_chromadb.py

    - name: Commit and Push Updates
      run: |
        git config --global user.email "actions@github.com"
        git config --global user.name "GitHub Actions"
        git add trending_movies.json movie_embeddings.json chroma_db/*
        git commit -m "Auto-update movies database [skip ci]" || echo "No changes to commit"
        git push

  deploy-to-huggingface:
    needs: update-database
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Clone Hugging Face Space
      env:
        HF_TOKEN: ${{ secrets.HF_TOKEN }}
      run: |
        git clone https://$HF_TOKEN@huggingface.co/spaces/thanhtungvudata/CineMood3 hf-space

    - name: Copy Updated Data to Hugging Face Repo
      run: |
        rsync -av --exclude='.git' trending_movies.json movie_embeddings.json chroma_db/ hf-space/

    - name: Commit and Push Updates to Hugging Face
      env:
        HF_TOKEN: ${{ secrets.HF_TOKEN }}
      run: |
        cd hf-space
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git config --global user.name "GitHub Actions"
        git add .
        git commit -m "Auto-update from GitHub" || echo "No changes to commit"
        git push https://$HF_TOKEN@huggingface.co/spaces/thanhtungvudata/CineMood3.git HEAD:main


